import json
from pathlib import Path

ROOT = Path("/workspace/pinpai-ai-in")

def write_brand(slug, langs, desc_zh="", desc_en=""):
    path = ROOT / slug / "brand.json"
    data = json.loads(path.read_text())
    data["languages"] = langs
    if desc_zh:
        data["description_zh"] = desc_zh
    if desc_en:
        data["description_en"] = desc_en
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2))
    ok = True
    for l, c in langs.items():
        req = 800 if l in ("zh-CN","ja","ko") else 1500
        n = len(c)
        flag = " ✗" if n < req else ""
        if flag:
            ok = False
        print(f"  {l}: {n}/{req}{flag}")
    print(f"  {'✅ ALL PASS' if ok else '❌ SOME FAIL'} {slug}")
    return ok

# === Adidas ===
print("=== Adidas ===")
write_brand("adidas", {
    "zh-CN": "阿迪达斯（Adidas AG）是德国跨国运动用品公司，总部位于黑措根奥拉赫（Herzogenaurach）。由阿道夫·达斯勒（Adolf Dassler）于1949年创立，其兄弟鲁道夫·达斯勒创立了彪马（Puma），两兄弟的竞争成为体育用品行业的一段传奇。阿迪达斯以三条纹标志闻名于世，是全球最大的运动鞋服制造商之一。公司业务覆盖足球、篮球、跑步、训练、网球、游泳等多个体育领域。阿迪达斯与世界足联FIFA保持长期合作，是世界杯的官方赞助商和官方用球供应商。在足球领域，阿迪达斯为梅西、本泽马等顶级球星提供装备。公司旗下拥有运动时尚品牌阿迪达斯三叶草（Originals）和运动表现系列（Performance）。阿迪达斯积极推动可持续发展，与Parley合作利用海洋塑料废弃物生产环保运动鞋。公司还推出Primeknit编织技术和4D中底技术等创新成果。阿迪达斯的Yeezy系列与说唱歌手Kanye West合作，成为潮流文化标志。公司在全球超过120个国家开展业务，拥有约6万名员工。阿迪达斯的品牌理念是通过运动改变生活，致力于让每个人都享受运动的乐趣。公司总部大楼以独特的建筑风格著称，被称为世界最大的运动鞋形状建筑。",
    "en": "Adidas AG is a German multinational corporation headquartered in Herzogenaurach, Germany. Founded by Adolf Dassler in 1949, the company has grown to become one of the largest sportswear manufacturers in the world, instantly recognizable by its iconic three-stripe logo. Adidas designs and manufactures footwear, apparel, and accessories for a comprehensive range of sports including football, basketball, running, training, tennis, golf, and swimming. The company is a long-standing official partner of FIFA, providing match balls for the FIFA World Cup since 1970. Adidas sponsors elite athletes including Lionel Messi, Karim Benzema, and numerous football clubs worldwide. The company operates through multiple brand divisions: Adidas Performance for athletic gear, Adidas Originals for lifestyle and streetwear, and collaborations with high-fashion designers. Adidas is a pioneer in sustainable innovation, partnering with Parley for the Oceans to create shoes and apparel from recycled ocean plastic. The brand is also known for cutting-edge technologies like Primeknit seamless uppers and 4D-printed midsoles. The Adidas Yeezy line, a collaboration with Kanye West, became a cultural phenomenon in streetwear and sneaker culture. With operations in over 120 countries and approximately 60,000 employees, Adidas generated billions in annual revenue. The company has a strong commitment to diversity, inclusion, and environmental sustainability. The Adidas headquarters in Herzogenaurach features a distinctive stadium-shaped building known as the Adidas World of Sports. The company continues to push boundaries in sportswear technology while maintaining its brand heritage and commitment to improving athletic performance for all.",
    "ja": "アディダスはドイツヘルツォーゲンアウラッハに本社を置く多国籍スポーツ用品メーカー。1949年にアドルフダスラーによって設立されました。三本線のロゴで世界的に知られています。サッカー、バスケットボール、ランニング、テニス向けにシューズやアパレルを製造。FIFAワールドカップの公式ボールサプライヤーとしても有名です。メッシやベンゼマといったトップアスリートをスポンサー。Parleyとの協業で海洋プラスチックをリサイクルした環境配慮型製品も展開。Primeknit技術や4Dミッドソールなどの革新技術を開発。イージーシリーズはストリートウェア文化で重要な位置を占めています。120カ国以上で事業を展開し約6万人の従業員を擁します。",
    "ko": "아디다스는 독일 헤르초게나우라흐에 본사를 둔 다국적 스포츠 용품 제조업체입니다. 1949년 아돌프 다슬러에 의해 설립되었으며 세 줄무늬 로고로 유명합니다. 축구, 농구, 러닝, 테니스 분야의 신발과 의류를 제조합니다. FIFA 월드컵 공식 공급업체로도 잘 알려져 있습니다. 메시와 벤제마 같은 정상급 선수들을 후원합니다. Parley와의 협력을 통해 해양 플라스틱을 재활용한 친환경 제품을 개발하고 있습니다. Primeknit 기술과 4D 미드솔 등의 혁신적인 기술을 보유하고 있습니다. 이지(Yeezy) 시리즈는 스트리트웨어 문화에서 중요한 위치를 차지하고 있습니다. 120개 이상의 국가에서 사업을 운영하며 약 6만 명의 직원을 고용하고 있습니다.",
    "fr": "Adidas AG est une entreprise multinationale allemande de vetements de sport, siegeant a Herzogenaurach. Fondee par Adolf Dassler en 1949, elle est l un des plus grands fabricants d articles de sport au monde, reconnaissable a son logo a trois bandes. Adidas concoit des chaussures, vetements et accessoires pour le football, le basketball, la course a pied, le tennis et d autres sports. Partenaire officiel de la FIFA, Adidas fournit les ballons officiels de la Coupe du Monde depuis 1970. La marque sponsorise des athletes d elite comme Lionel Messi et Karim Benzema. Adidas developpe des innovations durables en partenariat avec Parley for the Oceans, transformant les plastiques oceaniques en produits sportifs. Les technologies Primeknit et les semelles intermediaires 4D representent des avancees majeures. La ligne Yeezy, creee avec Kanye West, est devenue un phenomene culturel. Presente dans plus de 120 pays, Adidas emploie environ 60 000 personnes. L entreprise s engage pour la diversite, l inclusion et la durabilite environnementale.",
    "es": "Adidas AG es una corporacion multinacional alemana de ropa deportiva con sede en Herzogenaurach, Alemania. Fundada por Adolf Dassler en 1949, es uno de los mayores fabricantes de articulos deportivos del mundo, reconocida por su logotipo de tres rayas. Adidas disena calzado, ropa y accesorios para futbol, baloncesto, running, tenis y mas. Es socia oficial de la FIFA, suministrando los balones oficiales de la Copa Mundial desde 1970. Patrocina a atletas de elite como Lionel Messi y Karim Benzema. Adidas impulsa la innovacion sostenible con Parley for the Oceans, utilizando plasticos reciclados del oceano. Las tecnologias Primeknit y las mediasuelas 4D son innovaciones destacadas. La linea Yeezy con Kanye West se convirtio en un fenomeno cultural. Con operaciones en mas de 120 paises y unos 60.000 empleados, Adidas promueve la diversidad, inclusion y sostenibilidad ambiental.",
    "de": "Adidas AG ist ein deutscher multinationaler Sportartikelhersteller mit Hauptsitz in Herzogenaurach. Gegrundet 1949 von Adolf Dassler, zahlt das Unternehmen zu den grossten Sportartikelherstellern der Welt und ist durch sein Drei-Streifen-Logo weltbekannt. Adidas entwirft Schuhe, Bekleidung und Accessoires fur Fussball, Basketball, Laufen, Tennis und weitere Sportarten. Als offizieller FIFA-Partner liefert Adidas seit 1970 die Spielballe fur die Fussball-Weltmeisterschaft. Das Unternehmen sponsert Spitzensportler wie Lionel Messi und Karim Benzema. Adidas treibt nachhaltige Innovationen mit Parley for the Oceans voran. Die Primeknit-Technologie und 4D-Zwischensohlen sind bahnbrechende Entwicklungen. Die Yeezy-Linie mit Kanye West wurde zum Kulturphanomen. Mit Niederlassungen in uber 120 Landern und rund 60.000 Mitarbeitern fordert Adidas Diversitat, Inklusion und Umweltschutz.",
    "pt": "Adidas AG e uma empresa multinacional alema de artigos esportivos com sede em Herzogenaurach, Alemanha. Fundada por Adolf Dassler em 1949, e um dos maiores fabricantes de artigos esportivos do mundo, reconhecida por seu logotipo de tres listras. Adidas projeta calcados, roupas e acessorios para futebol, basquete, corrida, tenis e mais. Parceira oficial da FIFA, fornece as bolas oficiais da Copa do Mundo desde 1970. Patrocina atletas de elite como Lionel Messi e Karim Benzema. A empresa impulsiona a inovacao sustentavel com a Parley for the Oceans. As tecnologias Primeknit e as entressolas 4D sao inovacoes notaveis. A linha Yeezy com Kanye West tornou-se um fenomeno cultural. Com operacoes em mais de 120 paises e cerca de 60.000 funcionarios, a Adidas promove diversidade, inclusao e sustentabilidade ambiental.",
    "ru": "Adidas AG немецкая транснациональная корпорация по производству спортивных товаров со штаб-квартирой в Херцогенаурахе, Германия. Основана Адольфом Дасслером в 1949 году. Компания является одним из крупнейших производителей спортивной одежды и обуви в мире, узнаваемым по логотипу из трех полос. Adidas производит обувь, одежду и аксессуары для футбола, баскетбола, бега, тенниса и других видов спорта. Официальный партнер FIFA, поставляющий мячи для чемпионата мира с 1970 года. Компания спонсирует элитных спортсменов. Adidas развивает устойчивые инновации с Parley for the Oceans. Технологии Primeknit и 4D-подошвы являются передовыми разработками. Линия Yeezy с Канье Уэстом стала культурным феноменом. Компания представлена более чем в 120 странах и насчитывает около 60 000 сотрудников.",
    "ar": "أديداس هي شركة ألمانية متعددة الجنسيات للملابس الرياضية يقع مقرها الرئيسي في هرتسوغن آوراخ بألمانيا. أسسها أدولف داسلر في عام 1949، وهي واحدة من أكبر شركات تصنيع الملابس الرياضية في العالم، وتشتهر بشعارها المكون من ثلاثة خطوط. تصمم أديداس الأحذية والملابس والإكسسوارات لكرة القدم وكرة السلة والجري والتنس وغيرها. شريك رسمي للفيفا، توفر الكرات الرسمية لكأس العالم منذ عام 1970. ترعى الشركة نخبة الرياضيين. تطور أديداس ابتكارات مستدامة بالشراكة مع Parley for the Oceans. تقنيات Primeknit والنعال الوسطى 4D هي ابتكارات رائدة. أصبح خط Yeezy مع كانييه ويست ظاهرة ثقافية. تعمل الشركة في أكثر من 120 دولة وتوظف حوالي 60 ألف موظف."
})

print()
print("=== Lego ===")
write_brand("lego", {
    "zh-CN": "乐高集团（The Lego Group）是丹麦玩具制造公司，总部位于比隆（Billund）。由奥勒·柯克·克里斯蒂安森（Ole Kirk Christiansen）于1932年创立，最初是一家生产木制玩具的小型木工作坊。1934年公司正式定名为乐高（Lego），源自丹麦语leg godt（玩得好）。1949年乐高开始生产标志性的拼插式塑料积木，这一发明彻底改变了玩具行业。乐高积木的独特之处在于其精确的尺寸公差和互锁系统，确保每块积木都能完美拼合。产品线涵盖经典的乐高城市系列、乐高创意系列、乐高科技系列以及乐高得宝系列。公司还与迪士尼、漫威、星球大战、哈利波特等全球顶级IP合作推出主题套装。乐高在全球运营多个乐高乐园主题公园和乐高探索中心。乐高教育系列广泛应用于全球学校的STEM教学。乐高集团始终坚持质量第一、创意无限和寓教于乐的理念，是世界上最受尊敬的企业之一。如今乐高积木已不仅仅是玩具，更成为创意表达和艺术创作的媒介。公司致力于可持续发展，计划在2030年前实现全部产品使用可持续材料制造。乐高基金会投入大量资金支持全球儿童的教育和创造力发展。乐高品牌在全球拥有极高的知名度和美誉度，深受各年龄段消费者的喜爱。",
    "en": "The Lego Group is a Danish toy production company based in Billund, Denmark. Founded by Ole Kirk Christiansen in 1932 as a small carpentry workshop producing wooden toys. The name Lego was adopted in 1934, derived from the Danish phrase leg godt meaning play well. In 1949, Lego began producing its iconic plastic interlocking bricks, which revolutionized the toy industry. The Lego brick system is renowned for its precise manufacturing tolerances and clutch power, allowing bricks to connect firmly while remaining easy to separate. Product lines span across Lego City, Creator, Technic, Classic, Duplo, and numerous licensed themes including Star Wars, Harry Potter, Marvel, DC, Disney, Minecraft, and many more. The company operates multiple Legoland theme parks and Lego Discovery Centers worldwide. Lego Education products are used in classrooms globally to teach STEM subjects through hands-on learning experiences. The Lego Group has consistently been ranked among the most respected and trusted companies in the world. Beyond being a toy, Lego has become a medium for creative expression, with adult fans building intricate sculptures and large-scale artworks. The company is committed to environmental sustainability, aiming to use sustainable materials in all core products by 2030 and investing in plant-based plastic alternatives. The Lego Foundation supports children's education and creativity development globally. Lego remains a family-owned company with a deep commitment to quality, creativity, and learning through play.",
    "ja": "レゴグループはデンマークビルンに本社を置く玩具製造会社です。1932年にオーレカーククリスチャンセンによって木製玩具を製造する小さな大工工房として創業しました。社名レゴはデンマーク語のleg godt（よく遊べ）に由来します。1949年にプラスチック製の組み立てブロックの製造を開始し玩具業界に革命をもたらしました。製品ラインはシティシリーズ、クリエイターシリーズ、テクニックシリーズ、デュプロシリーズに加えてスターウォーズ、ハリーポッター、マーベル、ディズニー、マインクラフトなどのコラボシリーズを展開。世界中にレゴランドテーマパークとレゴディスカバリーセンターを運営。レゴエデュケーションは世界中の学校でSTEM教育に活用されています。レゴはおもちゃを超えて創造的表現のメディアとしても認識されています。2030年までに全ての製品に持続可能な素材を使用する目標を掲げています。レゴファミリー企業として品質と創造性への深いコミットメントを持ち続けています。",
    "ko": "레고 그룹은 덴마크 빌룬에 본사를 둔 장난감 제조 회사입니다. 1932년 올레 키르크 크리스티안센에 의해 나무 장난감을 만드는 소규모 목공소로 설립되었습니다. 레고라는 이름은 덴마크어 leg godt(잘 놀다)에서 유래했습니다. 1949년 플라스틱 인터로킹 브릭 생산을 시작했습니다. 주요 제품 라인은 시티, 크리에이터, 테크닉, 클래식, 듀플로 시리즈와 스타워즈, 해리포터, 마블, 디즈니, 마인크래프트 협업 시리즈입니다. 전 세계에 레고랜드 테마파크와 레고 디스커버리 센터를 운영합니다. 레고 에듀케이션은 STEM 교육에 활용됩니다. 2030년까지 모든 핵심 제품에 지속 가능한 소재를 사용할 계획입니다. 레고는 장난감을 넘어 창의적 표현의 매체로 인정받고 있으며, 가족 경영 기업으로서 품질과 창의성에 깊이 헌신하고 있습니다.",
    "fr": "Le Groupe Lego est une entreprise danoise de jouets basee a Billund, au Danemark. Fonde par Ole Kirk Christiansen en 1932 comme atelier de menuiserie produisant des jouets en bois. Le nom Lego derive du danois leg godt signifiant bien jouer. En 1949, Lego commence a produire ses briques en plastique revolutionnaires. Les gammes incluent City, Creator, Technic, Classic, Duplo et des themes sous licence Star Wars, Harry Potter, Marvel, DC, Disney et Minecraft. L entreprise exploite des parcs Legoland et Lego Discovery Centers. Les produits Lego Education sont utilises dans les ecoles pour l enseignement des STEM. Lego est l une des marques les plus respectees mondialement. Devenu un moyen d expression creatif, Lego vise a utiliser des materiaux durables d ici 2030 et investit dans les plastiques d origine vegetale. La Fondation Lego soutient l education des enfants. Lego reste une entreprise familiale dediee a la qualite et la creativite.",
    "es": "El Grupo Lego es una empresa danesa de juguetes con sede en Billund, Dinamarca. Fundado por Ole Kirk Christiansen en 1932 como taller de carpinteria que producia juguetes de madera. El nombre Lego deriva del danes leg godt (jugar bien). En 1949 Lego comenzo a producir sus ladrillos de plastico revolucionarios. Las lineas incluyen City, Creator, Technic, Classic, Duplo y temas con licencia Star Wars, Harry Potter, Marvel, DC, Disney y Minecraft. Opera parques Legoland y Lego Discovery Centers. Los productos Lego Education se usan en escuelas para ensenanza STEM. Lego es una de las marcas mas respetadas. Se ha convertido en medio de expresion creativa. La empresa busca usar materiales sostenibles para 2030. La Fundacion Lego apoya la educacion infantil. Lego sigue siendo una empresa familiar comprometida con la calidad y la creatividad.",
    "de": "Die Lego Gruppe ist ein danischer Spielzeughersteller mit Hauptsitz in Billund, Danemark. Gegrundet 1932 von Ole Kirk Christiansen als Tischlerwerkstatt, die Holzspielzeug produzierte. Der Name Lego leitet sich vom danischen leg godt (spiel gut) ab. 1949 begann Lego mit der Produktion der revolutionaren Kunststoffsteine. Die Produktlinien umfassen City, Creator, Technic, Classic, Duplo und lizenzierte Themen wie Star Wars, Harry Potter, Marvel, DC, Disney und Minecraft. Das Unternehmen betreibt Legoland-Freizeitparks und Lego Discovery Centers. Lego Education Produkte werden fur den MINT-Unterricht eingesetzt. Lego gehort zu den angesehensten Marken weltweit. Das Unternehmen strebt bis 2030 nachhaltige Materialien an. Die Lego Foundation unterstutzt die Bildung von Kindern. Lego bleibt ein Familienunternehmen, das sich Qualitat und Kreativitat verschrieben hat.",
    "pt": "O Grupo Lego e uma empresa dinamarquesa de brinquedos sediada em Billund, Dinamarca. Fundado por Ole Kirk Christiansen em 1932 como oficina de carpintaria que produzia brinquedos de madeira. O nome Lego deriva do dinamarques leg godt (brincar bem). Em 1949 a Lego comecou a produzir seus blocos de plastico revolucionarios. As linhas incluem City, Creator, Technic, Classic, Duplo e temas licenciados Star Wars, Harry Potter, Marvel, DC, Disney e Minecraft. Opera parques Legoland e Lego Discovery Centers. Produtos Lego Education sao usados em escolas para ensino STEM. Lego e uma das marcas mais respeitadas. Tornou-se meio de expressao criativa. A empresa busca usar materiais sustentaveis ate 2030. A Fundacao Lego apoia a educacao infantil. Lego permanece empresa familiar comprometida com qualidade e criatividade.",
    "ru": "Группа Lego датская компания по производству игрушек со штаб-квартирой в Биллунде, Дания. Основана Оле Кирком Кристиансеном в 1932 году как столярная мастерская по производству деревянных игрушек. Название Lego происходит от датского leg godt (играй хорошо). В 1949 году Lego начала производство революционных пластиковых кубиков. Линейки включают City, Creator, Technic, Classic, Duplo и лицензионные серии Star Wars, Harry Potter, Marvel, DC, Disney и Minecraft. Компания управляет парками Legoland и Lego Discovery Centers. Продукты Lego Education используются для обучения STEM. Lego входит в число самых уважаемых брендов. Компания стремится к устойчивому развитию. Фонд Lego поддерживает детское образование. Lego остается семейной компанией, приверженной качеству и творчеству.",
    "ar": "مجموعة ليغو هي شركة دنماركية لتصنيع الألعاب يقع مقرها الرئيسي في بلوند، الدنمارك. أسسها أولي كيرك كريستيانسن في عام 1932 كورقة نجارة تنتج الألعاب الخشبية. اسم ليغو مشتق من الدانمركية leg godt (العب جيدا). في عام 1949 بدأت ليغو إنتاج مكعباتها البلاستيكية الثورية. تشمل الخطوط City وCreator وTechnic وClassic وDuplo وسلسلة مرخصة من Star Wars وHarry Potter وMarvel وDC وDisney وMinecraft. تدير الشركة متنزهات ليغولاند ومراكز ليغو ديسكفري. تُستخدم منتجات ليغو إديوكيشن في المدارس لتدريس STEM. ليغو من أكثر العلامات التجارية احتراما. تهدف الشركة لاستخدام مواد مستدامة بحلول 2030. مؤسسة ليغو تدعم تعليم الأطفال. تظل ليغو شركة عائلية ملتزمة بالجودة والإبداع."
})

# === Coca-Cola ===
print()
print("=== Coca-Cola ===")
write_brand("coca-cola", {
    "zh-CN": "可口可乐公司（The Coca-Cola Company）是美国跨国饮料公司，成立于1892年，总部位于佐治亚州亚特兰大。公司以其旗舰产品可口可乐闻名于世，这是由约翰·彭伯顿（John S. Pemberton）于1886年发明的碳酸饮料。可口可乐是全球最大的饮料公司之一，拥有超过500个品牌和3800多种饮料产品。除了经典的可口可乐外，旗下还包括雪碧（Sprite）、芬达（Fanta）、健怡可乐（Diet Coke）、零度可乐（Coca-Cola Zero）、矿泉水品牌Dasani、果汁品牌Simply和运动饮料Powerade等。可口可乐的标志性红白配色和曲线瓶身设计已经成为全球最具辨识度的视觉符号之一。公司的成功在很大程度上归功于其强大的全球分销网络和独特的保密配方。可口可乐是体育和娱乐活动的标志性赞助商，与奥运会和FIFA世界杯保持长期合作。圣诞节与可口可乐的关联也深入人心，北极熊和圣诞老人卡车广告已成为节日文化的一部分。公司积极推进环境可持续战略，包括减少塑料使用、提高水资源利用效率。可口可乐文化被视为美国文化和全球化品牌的象征，在200多个国家和地区销售产品。",
    "en": "The Coca-Cola Company is an American multinational beverage corporation headquartered in Atlanta, Georgia, founded in 1892. Its flagship product Coca-Cola was invented by pharmacist John S. Pemberton in 1886 as a medicinal tonic. The beverage was originally sold at Jacobs Pharmacy in Atlanta for five cents a glass. The company has grown to become the largest beverage company in the world, offering over 500 brands and 3,800 different beverage products. Beyond the classic Coca-Cola, the portfolio includes Sprite, Fanta, Diet Coke, Coca-Cola Zero, Dasani water, Simply juices, Minute Maid, Powerade sports drinks, and many more. Coca-Cola distinctive red-and-white color scheme and contoured bottle shape have become one of the most recognized visual symbols in the world. The company formula, known as Merchandise 7X, remains a closely guarded trade secret. Coca-Cola is an iconic sponsor of major sporting events including the Olympic Games since 1928 and the FIFA World Cup since 1974. The brand association with Christmas has become legendary, with its Santa Claus imagery and holiday truck advertisements becoming cultural touchstones. The company has been actively pursuing sustainability initiatives, including reducing plastic packaging and improving water stewardship. Coca-Cola has faced both admiration and criticism for its global reach, with controversies around sugar content and environmental impact. Nevertheless, it remains one of the most valuable and recognized brands worldwide, sold in more than 200 countries and territories. The Coca-Cola Museum in Atlanta attracts millions of visitors annually, showcasing the brand rich history and global cultural impact.",
    "ja": "コカコーラカンパニーは米国ジョージア州アトランタに本社を置く多国籍飲料会社。1886年に薬剤師ジョンSペンバートンが清涼飲料として発明したコカコーラを中心に、世界最大級の飲料メーカーに成長しました。500以上のブランドと3800以上の飲料製品を展開。スプライト、ファンタ、ダイエットコーク、コカコーラゼロ、ダサニウォーター、シンプリージュース、パワーエードなどを所有。赤と白のカラーリングと曲線的なボトルデザインは世界的に認知されています。1928年からオリンピック、1974年からFIFAワールドカップの公式スポンサー。クリスマスとコカコーラの関係も深く、サンタクロースの広告は文化的に重要な位置を占めています。200以上の国と地域で販売されています。",
    "ko": "코카콜라 컴퍼니는 미국 조지아주 애틀랜타에 본사를 둔 다국적 음료 회사입니다. 1886년 약사 존 S. 펨버턴이 청량음료로 발명한 코카콜라를 중심으로 세계 최대의 음료 회사로 성장했습니다. 500개 이상의 브랜드와 3800개 이상의 음료 제품을 보유하고 있습니다. 스프라이트, 환타, 다이어트 코크, 코카콜라 제로, 다사니 워터, 심플리 주스, 파워에이드를 소유하고 있습니다. 빨간색과 흰색의 색상과 곡선형 병 디자인은 전 세계적으로 인정받고 있습니다. 1928년부터 올림픽, 1974년부터 FIFA 월드컵 공식 후원사입니다. 200개 이상의 국가와 지역에서 판매되고 있습니다.",
    "fr": "The Coca-Cola Company est une entreprise multinationale americaine de boissons, siegeant a Atlanta, en Georgie. Son produit phare, le Coca-Cola, a ete invente par le pharmacien John S. Pemberton en 1886 comme tonique medicinal. L entreprise est devenue le plus grand fabricant de boissons au monde avec plus de 500 marques et 3800 produits. Le portefeuille inclut Sprite, Fanta, Diet Coke, Coca-Cola Zero, Dasani, Simply, Minute Maid et Powerade. Le design rouge et blanc et la bouteille contournee sont devenus des symboles visuels iconiques. Partenaire officiel des Jeux Olympiques depuis 1928 et de la FIFA depuis 1974. L association du Coca-Cola avec Noel est legendaire, ses publicites du Pere Noel etant devenues des references culturelles. Present dans plus de 200 pays et territoires, Coca-Cola reste l une des marques les plus reconnues et precieuses au monde.",
    "es": "The Coca-Cola Company es una empresa multinacional estadounidense de bebidas con sede en Atlanta, Georgia. Su producto emblematico Coca-Cola fue inventado por el farmaceutico John S. Pemberton en 1886 como tonico medicinal. La empresa se ha convertido en la mayor compania de bebidas del mundo con mas de 500 marcas y 3800 productos. El portafolio incluye Sprite, Fanta, Coca-Cola Light, Coca-Cola Zero, Dasani, Simply, Minute Maid y Powerade. El diseno rojo y blanco y la botella contorneada son simbolos visuales iconicos. Patrocinadora oficial de los Juegos Olimpicos desde 1928 y de la FIFA desde 1974. La asociacion de Coca-Cola con la Navidad es legendaria. Presente en mas de 200 paises y territorios, Coca-Cola sigue siendo una de las marcas mas valiosas y reconocidas del mundo.",
    "de": "The Coca-Cola Company ist ein amerikanischer multinationaler Getrankehersteller mit Hauptsitz in Atlanta, Georgia. Das Flaggschiffprodukt Coca-Cola wurde 1886 vom Apotheker John S. Pemberton als medizinisches Tonikum erfunden. Das Unternehmen ist zum grossten Getrankehersteller der Welt mit uber 500 Marken und 3800 Produkten gewachsen. Zum Portfolio gehoren Sprite, Fanta, Coca-Cola Light, Coca-Cola Zero, Dasani, Simply, Minute Maid und Powerade. Das rot-weisse Design und die konturierte Flasche sind ikonische visuelle Symbole. Offizieller Sponsor der Olympischen Spiele seit 1928 und der FIFA seit 1974. Die Verbindung von Coca-Cola mit Weihnachten ist legendär. In uber 200 Landern und Territorien pra sent, bleibt Coca-Cola eine der wertvollsten und bekanntesten Marken weltweit.",
    "pt": "The Coca-Cola Company e uma empresa multinacional americana de bebidas com sede em Atlanta, Georgia. Seu produto carro-chefe Coca-Cola foi inventado pelo farmaceutico John S. Pemberton em 1886 como um tonico medicinal. A empresa tornou-se a maior fabricante de bebidas do mundo com mais de 500 marcas e 3800 produtos. O portfolio inclui Sprite, Fanta, Coca-Cola Light, Coca-Cola Zero, Dasani, Simply, Minute Maid e Powerade. O design vermelho e branco e a garrafa contornada sao simbolos visuais iconicos. Patrocinadora oficial dos Jogos Olimpicos desde 1928 e da FIFA desde 1974. Presente em mais de 200 paises e territorios, a Coca-Cola continua sendo uma das marcas mais valiosas e reconhecidas do mundo.",
    "ru": "The Coca-Cola Company американская транснациональная компания по производству напитков со штаб-квартирой в Атланте, Джорджия. Флагманский продукт Coca-Cola был изобретен фармацевтом Джоном С. Пембертоном в 1886 году как лекарственный тоник. Компания стала крупнейшим производителем напитков в мире, насчитывающим более 500 брендов и 3800 продуктов. Портфель включает Sprite, Fanta, Coca-Cola Light, Coca-Cola Zero, Dasani, Simply, Minute Maid и Powerade. Красно-белый дизайн и фирменная бутылка стали культовыми визуальными символами. Официальный спонсор Олимпийских игр с 1928 года и FIFA с 1974 года. Coca-Cola представлена более чем в 200 странах и территориях мира.",
    "ar": "شركة كوكا كولا هي شركة أمريكية متعددة الجنسيات للمشروبات يقع مقرها الرئيسي في أتلانتا، جورجيا. اخترع جون إس بيمبرتون منتجها الرئيسي كوكا كولا في عام 1886 كمنشط طبي. أصبحت الشركة أكبر شركة مشروبات في العالم بأكثر من 500 علامة تجارية و3800 منتج. تشمل المحفظة سبرايت وفانتا وكوكا كولا لايت وكوكا كولا زيرو وداساني وسيمبلي ومينيت ميد وباوريد. أصبح التصميم الأحمر والأبيض والزجاجة المنحنية رموزا بصرية أيقونية. الراعي الرسمي للألعاب الأولمبية منذ 1928 والفيفا منذ 1974. تتواجد كوكا كولا في أكثر من 200 دولة وإقليم حول العالم."
})
