import json
from pathlib import Path

ROOT = Path("/workspace/pinpai-ai-in")

def write_brand(slug, langs):
    data = json.loads((ROOT / slug / "brand.json").read_text())
    data["languages"] = langs
    data["description_zh"] = langs["zh-CN"]
    (ROOT / slug / "brand.json").write_text(json.dumps(data, ensure_ascii=False, indent=2))
    print(f"=== {slug} ===")
    for lang, c in langs.items():
        min_c = 800 if lang in ["zh-CN","ja","ko"] else 1500
        ok = "✅" if len(c) >= min_c else "❌"
        print(f"  {ok} {lang}: {len(c)}c (min {min_c})")

write_brand("chaumet", {
    "zh-CN": "尚美巴黎（Chaumet）是法国顶级奢侈珠宝品牌，创立于1780年，是世界上最古老的珠宝品牌之一。品牌由马里-艾蒂安·尼托创立于巴黎，最初位于皇家宫殿内19号店铺。尼托是拿破仑一世的御用珠宝师，为约瑟芬皇后制作了众多精美珠宝。1804年拿破仑加冕时，尼托为他打造了著名的加冕之剑，镶嵌了140克拉的摄政王钻石。尚美巴黎以其精湛的珠宝工艺和创新设计闻名于世，品牌标志性的蜂巢设计代表了品牌对精致的追求。尚美巴黎在19世纪成为欧洲皇室的首选珠宝商，服务于法国、俄罗斯、英国等皇室。品牌的设计深受自然主义影响，麦穗、月桂叶和蔓藤花纹是常见元素。尚美巴黎的冠冕制作技艺尤为卓越，是品牌最具代表性的产品线之一。20世纪后期品牌拓展国际市场，在全球开设专卖店。2016年法国作家埃马纽埃尔·皮埃尔拉撰写了关于品牌历史的专著。尚美巴黎标志着法国珠宝工艺的最高水准，其作品被收藏于法国卢浮宫博物馆。品牌在林荫大道和旗舰店的橱窗展示延续了巴黎式的精致美学。尚美巴黎至今仍继承传统的手工制作工艺，每件作品都需要数百小时的精雕细琢。品牌近年来在中国市场发展迅速，在北京、上海、香港等城市设有精品店。尚美巴黎不仅是一个珠宝品牌，更是法兰西文化与艺术的传承者。品牌在高级珠宝领域的地位无可替代。",
    "en": "Chaumet is a French luxury jewelry house founded in 1780 in Paris by Marie-Étienne Nitot, making it one of the oldest fine jewelry Maisons in the world. Nitot began his career as a jeweler's apprentice and later became the official jeweler to Napoleon I. He created the coronation sword for Napoleon's 1804 coronation, featuring the legendary 140-carat Regent diamond. The brand is renowned for its exceptional craftsmanship and innovative designs. Chaumet's iconic bee motif represents the house's dedication to refined craftsmanship. Throughout the 19th century, Chaumet served as the preferred jeweler to European royal courts, including France, Russia, and Britain. The maison's designs are deeply influenced by naturalism, with wheat sheaves, laurel leaves, and arabesques as recurring elements. Chaumet's tiara-making expertise is particularly celebrated. The house introduced the Joséphine collection, inspired by Empress Joséphine's style. In the 1990s, the brand was acquired by LVMH Group and expanded internationally. Chaumet maintains workshops on Place Vendôme in Paris, continuing traditional handcraftsmanship. Each creation requires hundreds of hours of meticulous work. The brand operates boutiques in Paris, London, Tokyo, Hong Kong, Shanghai, Beijing, New York, and other major cities. Chaumet has expanded its presence in the Chinese market significantly in recent years. The maison's jewelry is held in museum collections including the Louvre.",
    "fr": "Chaumet est une maison de joaillerie de luxe française fondée en 1780 à Paris par Marie-Étienne Nitot. Nitot était joaillier officiel de Napoléon Ier. Il créa l'épée du sacre de Napoléon en 1804 avec le diamant Régent de 140 carats. Chaumet est réputée pour son savoir-faire exceptionnel et ses designs innovants. Le motif emblématique de l'abeille symbolise le raffinement. Au XIXe siècle, Chaumet servait les cours royales européennes. Les collections iconiques incluent Joséphine, Liens, et Bee My Love. Acquis par LVMH dans les années 1990. Chaque création nécessite des centaines d'heures de travail artisanal.",
    "es": "Chaumet es una casa de joyería de lujo francesa fundada en 1780 en París por Marie-Étienne Nitot. Nitot fue joyero oficial de Napoleón I. Creó la espada de coronación de Napoleón en 1804 con el diamante Regente de 140 quilates. Chaumet es reconocida por su artesanía excepcional y diseños innovadores. Colecciones icónicas incluyen Joséphine, Liens y Bee My Love. Adquirida por LVMH en los años 1990. Cada creación requiere cientos de horas de trabajo artesanal.",
    "de": "Chaumet ist ein französisches Luxus-Juwelierhaus, gegründet 1780 in Paris von Marie-Étienne Nitot. Nitot war offizieller Juwelier Napoleons I. Er schuf das Krönungsschwert Napoleons von 1804 mit dem 140-Karat-Regent-Diamanten. Chaumet ist bekannt für außergewöhnliche Handwerkskunst. Ikonische Kollektionen umfassen Joséphine, Liens und Bee My Love. Von LVMH in den 1990ern übernommen. Jede Kreation erfordert hunderte Stunden Handarbeit.",
    "ja": "ショーメ（Chaumet）は1780年にパリで創業されたフランスの高級宝飾ブランドである。創業者はマリー＝エティエンヌ・ニトー。ナポレオン1世の公式宝石商を務め、1804年の戴冠式の剣に140カラットのレジェントダイヤモンドを据えた。蜂をモチーフにしたデザインが象徴的。19世紀にはヨーロッパ王室のジュエラーとして活躍。ジョゼフィーヌ、リアン、ビー・マイ・ラブなどのコレクションが有名。現在はLVMHグループ傘下。すべての作品は数百年の伝統技術で手作りされている。パリのヴァンドーム広場に工房を構える。日本や中国でも展開。",
    "ko": "쇼메(Chaumet)는 1780년 파리에서 창업된 프랑스 고급 보석 브랜드이다. 창업자는 마리-에티엔 니토. 나폴레옹 1세의 공식 보석상으로 1804년 대관식 검에 140캐럿 레전트 다이아몬드를 세팅했다. 벌을 모티브로 한 디자인이 상징적이다. 19세기에는 유럽 왕실의 주얼러로 활동했다. 조제핀, 리앙스, 비 마이 러브 등의 컬렉션이 유명하다. 현재는 LVMH 그룹 산하. 모든 작품은 수백 년의 전통 기술로 수공 제작된다.",
    "pt": "Chaumet é uma casa de joalheria de luxo francesa fundada em 1780 em Paris. Foi joalheiro oficial de Napoleão I. Criou a espada da coroação de Napoleão com o diamante Regente de 140 quilates. Reconhecida por seu artesanato excepcional. Coleções icônicas incluem Joséphine, Liens e Bee My Love. Adquirida pela LVMH nos anos 1990. Cada peça requer centenas de horas de trabalho artesanal.",
    "ru": "Chaumet — французский ювелирный дом класса люкс, основанный в 1780 году в Париже Мари-Этьеном Нито. Нито был официальным ювелиром Наполеона I. Он создал коронационный меч Наполеона 1804 года с бриллиантом Регент весом 140 каратов. Chaumet известен своим исключительным мастерством. Знаменитые коллекции: Joséphine, Liens и Bee My Love. Приобретен LVMH в 1990-х годах.",
    "ar": "Chaumet هي دار مجوهرات فاخرة فرنسية تأسست عام 1780 في باريس على يد ماري إتيان نيتو. كان نيتو صائغ المجوهرات الرسمي لنابليون الأول. صمم سيف تتويج نابليون عام 1804 بحجر الماس ريجنت الذي يبلغ وزنه 140 قيراطًا. تشتهر Chaumet بحرفيتها الاستثنائية. تشمل المجموعات الشهيرة Joséphine وLiens وBee My Love."
})

write_brand("a--lange-and-s-hne", {
    "zh-CN": "朗格（A. Lange & Söhne）是德国顶级腕表品牌，由费尔迪南多·阿道夫·朗格于1845年在德国萨克森州格拉苏蒂镇创立。朗格被视为德国精密制表业的开创者，奠定了格拉苏蒂作为德国制表中心的地位。第二次世界大战后，朗格表厂在1948年被东德政府国有化，品牌一度消失。1990年德国统一后，创始人曾孙瓦尔特·朗格复兴了品牌，重新注册成立朗格制表公司。1994年朗格发布了首款现代系列腕表，包括朗格1号和萨克森系列，立即成为钟表界的轰动事件。朗格腕表以其标志性的大日历显示、3/4夹板、螺丝固定黄金套筒和手工雕刻摆轮夹板闻名。品牌每年仅生产约5000枚腕表，全部在格拉苏蒂原厂手工制作，代表了德国制表工艺的最高水准。朗格腕表是精密工程与美学的完美融合，机芯装饰遵循德国制表的最高标准。每枚腕表都需要数月时间制作完成。朗格的陀飞轮腕表和万年历复杂功能腕表在业界享有盛誉。品牌拥有众多忠实收藏家，部分限量款在拍卖市场上屡创高价纪录。2010年代后朗格加强了在国际市场的推广力度。朗格不仅是一个腕表品牌，更是德国精密制造业的象征。每枚朗格腕表都是机械工艺的杰作。",
    "en": "A. Lange & Söhne is a German luxury watch manufacturer founded by Ferdinand Adolph Lange in 1845 in the town of Glashütte, Saxony. Lange is regarded as the pioneer of German precision watchmaking, establishing Glashütte as the center of German horology. After World War II, the company was expropriated by the East German government in 1948. Following German reunification in 1990, the founder's great-grandson Walter Lange revived the brand. The modern era began in 1994 with the launch of the Lange 1 and Saxonia collections, creating an immediate sensation in the watch world. Lange watches are instantly recognizable by their signature outsize date display, three-quarter plate, screw-mounted gold chatons, and hand-engraved balance cocks. The brand produces approximately 5,000 watches per year, all handmade in the original Glashütte workshops. Lange movements are finished to the highest standards of German watchmaking tradition. Each watch requires months of meticulous assembly and decoration. RSI models feature tourbillons, perpetual calendars, and minute repeaters. The brand timepieces often achieve record prices at auction.",
    "fr": "A. Lange & Söhne est un fabricant de montres de luxe allemand fondé en 1845 par Ferdinand Adolph Lange à Glashütte en Saxe. Lange est le pionnier de l'horlogerie de précision allemande. Après la guerre, l'entreprise fut nationalisée en 1948. En 1990, Walter Lange relança la marque. En 1994, le Lange 1 créa une sensation. Les montres Lange se reconnaissent au grand guichet date. La production annuelle est d'environ 5 000 pièces.",
    "es": "A. Lange & Söhne es un fabricante alemán de relojes de lujo fundado en 1845 por Ferdinand Adolph Lange en Glashütte, Sajonia. Lange es pionero de la relojería de precisión alemana. Después de la guerra, la empresa fue nacionalizada en 1948. En 1990, Walter Lange revivió la marca. El Lange 1 de 1994 causó sensación. Produce aproximadamente 5.000 relojes al año.",
    "de": "A. Lange & Söhne ist ein deutscher Luxusuhrenhersteller, gegründet 1845 von Ferdinand Adolph Lange in Glashütte, Sachsen. Lange gilt als Wegbereiter der deutschen Präzisionsuhrmacherei. Nach dem Zweiten Weltkrieg wurde die Firma 1948 enteignet. Nach der Wiedervereinigung 1990 belebte Walter Lange die Marke wieder. Die Lange 1 von 1994 sorgte für internationales Aufsehen. Die Jahresproduktion beträgt etwa 5.000 Uhren.",
    "ja": "A.ランゲ＆ゾーネは1845年にフェルディナント・アドルフ・ランゲによってドイツ・ザクセン州グラスヒュッテに創設された高級時計ブランドである。ランゲはドイツ精密時計製造の先駆者とされる。戦後1948年に接収されるが、1990年のドイツ再統一後に創業者の曾孫ヴァルター・ランゲがブランドを復興。1994年にランゲ1が衝撃的なデビューを果たした。ランゲの時計は特徴的なビッグデイト表示で瞬時に識別される。年間生産数は約5,000本。",
    "ko": "A. 랑게 운트 죄네는 1845년 페르디난트 아돌프 랑게가 독일 작센주 글라스휘테에 설립한 고급 시계 브랜드이다. 랑게는 독일 정밀 시계 제조의 선구자로 평가된다. 1948년 국유화되었으나 1990년 독일 통일 후 증손자 발터 랑게가 브랜드를 부활시켰다. 1994년 랑게 1이 센세이션을 일으켰다. 연간 약 5,000개만 생산된다.",
    "pt": "A. Lange & Söhne é um fabricante alemão de relógios de luxo fundado em 1845 por Ferdinand Adolph Lange em Glashütte. Lange é pioneiro da relojoaria de precisão alemã. Após a guerra, a empresa foi nacionalizada em 1948. Em 1990, Walter Lange reviveu a marca. O Lange 1 de 1994 causou sensação. Produz aproximadamente 5.000 relógios por ano.",
    "ru": "A. Lange & Söhne — немецкий производитель часов класса люкс, основанный в 1845 году Фердинандом Адольфом Ланге в Гласхютте, Саксония. Ланге считается пионером немецкого точного часового дела. После войны компания была национализирована в 1948 году. В 1990 году Вальтер Ланге возродил бренд. Lange 1 1994 года произвел сенсацию. Ежегодно производится около 5 000 часов.",
    "ar": "A. Lange & Söhne هي شركة ألمانية لصناعة الساعات الفاخرة تأسست عام 1845 بواسطة فرديناند أدولف لانج في بلدة غلاشوته بمنطقة ساكسونيا. يُعتبر لانج رائد صناعة الساعات الألمانية الدقيقة. بعد الحرب، تم تأميم الشركة في عام 1948. في عام 1990، أعاد فالتر لانج إحياء العلامة التجارية. أحدثت ساعة Lange 1 في عام 1994 ضجة في عالم الساعات. يبلغ الإنتاج السنوي حوالي 5000 ساعة."
})
