import json
from pathlib import Path

ROOT = Path("/workspace/pinpai-ai-in")

def expand_brand(slug, langs):
    path = ROOT / slug / "brand.json"
    data = json.loads(path.read_text())
    data["languages"] = langs
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2))
    for l, c in langs.items():
        print(f"  {l}: {len(c)} chars")
    print(f"  OK {slug}")

# Lego
expand_brand("lego", {
    "zh-CN": "乐高集团（The Lego Group）是丹麦玩具制造公司，总部位于比隆（Billund）。由奥勒·柯克·克里斯蒂安森（Ole Kirk Christiansen）于1932年创立，最初是一家生产木制玩具的小型木工作坊。1934年公司正式定名为乐高（Lego），源自丹麦语leg godt（玩得好）。1949年，乐高开始生产标志性的拼插式塑料积木，这一发明彻底改变了玩具行业。乐高积木的独特之处在于其精确的尺寸公差和互锁系统，确保每块积木都能完美拼合。产品线涵盖经典的乐高城市系列、乐高创意系列、乐高科技系列以及乐高得宝系列。公司还与迪士尼、漫威、星球大战、哈利波特等全球顶级IP合作推出主题套装。乐高在全球运营多个乐高乐园主题公园和乐高探索中心。乐高教育系列广泛应用于全球学校的STEM教学。乐高集团始终坚持质量第一、创意无限和寓教于乐的理念，是世界上最受尊敬的企业之一。如今乐高积木已不仅仅是玩具，更成为创意表达和艺术创作的媒介。公司致力于可持续发展，计划在2030年前实现全部产品使用可持续材料制造。",
    "en": "The Lego Group is a Danish toy production company based in Billund, Denmark. Founded by Ole Kirk Christiansen in 1932, the company started as a small carpentry workshop producing wooden toys. The name Lego was adopted in 1934, derived from the Danish phrase leg godt meaning play well. In 1949, Lego began producing its iconic plastic interlocking bricks, which revolutionized the toy industry. The Lego brick system is renowned for its precise manufacturing tolerances and clutch power, allowing bricks to connect firmly. Product lines include Lego City, Lego Creator, Lego Technic, Lego Classic, Lego Duplo, and licensed themes including Star Wars, Harry Potter, Marvel, DC, Disney, and many more. The company operates multiple Legoland theme parks and Lego Discovery Centers worldwide. Lego Education products are used in classrooms globally to teach STEM subjects through hands-on learning. The Lego Group has consistently been ranked among the most respected and trusted companies in the world. Beyond being a toy, Lego has become a medium for creative expression, with adult fans building intricate sculptures and artworks. The company is committed to sustainability, aiming to use sustainable materials in all core products by 2030. Lego remains family-owned and committed to quality, creativity, and learning through play.",
    "ja": "レゴグループはデンマークビルンに本社を置く玩具製造会社です。1932年にオーレカーククリスチャンセンによって木製玩具を製造する小さな大工工房として創業しました。社名レゴはデンマーク語のleg godt（よく遊べ）に由来します。1949年にプラスチック製の組み立てブロックの製造を開始し、玩具業界に革命をもたらしました。レゴブロックは精密な製造公差とクラッチパワーで知られています。主な製品ラインにはシティシリーズ、クリエイターシリーズ、テクニックシリーズ、デュプロシリーズがあり、スターウォーズ、ハリーポッター、マーベル、ディズニーなどとのコラボレーションシリーズも展開。世界中にレゴランドテーマパークとレゴディスカバリーセンターを運営。レゴエデュケーションは世界中の学校でSTEM教育に活用されています。レゴは単なるおもちゃを超えて、創造的表現のメディアとしても認識されています。2030年までに全ての中核製品に持続可能な素材を使用することを目標としています。",
    "ko": "레고 그룹은 덴마크 빌룬에 본사를 둔 장난감 제조 회사입니다. 1932년 올레 키르크 크리스티안센에 의해 나무 장난감을 만드는 소규모 목공소로 설립되었습니다. 레고라는 이름은 덴마크어 leg godt(잘 놀다)에서 유래했습니다. 1949년 획기적인 플라스틱 인터로킹 브릭 생산을 시작했습니다. 레고 브릭은 정밀한 제조 공차로 유명합니다. 주요 제품 라인은 시티, 크리에이터, 테크닉, 클래식, 듀플로 시리즈와 스타워즈, 해리포터, 마블, 디즈니 협업 시리즈입니다. 전 세계에 레고랜드 테마파크와 레고 디스커버리 센터를 운영 중입니다. 레고 에듀케이션 제품은 STEM 교육에 활용됩니다. 레고는 장난감을 넘어 창의적 표현의 매체로 인정받고 있습니다. 2030년까지 모든 핵심 제품에 지속 가능한 소재를 사용할 계획입니다.",
    "fr": "Le Groupe Lego est une entreprise danoise de jouets basee a Billund, au Danemark. Fonde par Ole Kirk Christiansen en 1932 comme un petit atelier de menuiserie produisant des jouets en bois. Le nom Lego a ete adopte en 1934, derive du danois leg godt signifiant bien jouer. En 1949, Lego a commence a produire ses celebres briques en plastique a emboter, revolutionnant l industrie du jouet. Les gammes incluent Lego City, Creator, Technic, Classic, Duplo et des themes sous licence Star Wars, Harry Potter, Marvel, DC et Disney. L entreprise exploite plusieurs parcs Legoland et Lego Discovery Centers dans le monde. Les produits Lego Education sont utilises dans les ecoles pour l enseignement des STEM. Lego est reconnue comme l une des marques les plus respectees et dignes de confiance au monde. Au-dela du jouet, Lego est devenu un moyen d expression creatif, avec des fans adultes construisant des sculptures et oeuvres d art complexes. L entreprise s engage pour la durabilite, visant a utiliser des materiaux durables dans tous ses produits d ici 2030. Lego reste une entreprise familiale dediee a la qualite, la creativite et l apprentissage par le jeu.",
    "es": "El Grupo Lego es una empresa danesa de juguetes con sede en Billund, Dinamarca. Fundado por Ole Kirk Christiansen en 1932 como un pequeno taller de carpinteria que producia juguetes de madera. El nombre Lego fue adoptado en 1934, derivado de la frase danesa leg godt (jugar bien). En 1949, Lego comenzo a producir sus iconicos ladrillos de plastico entrelazables, revolucionando la industria del juguete. Las lineas de productos incluyen Lego City, Creator, Technic, Classic, Duplo y temas con licencia de Star Wars, Harry Potter, Marvel, DC y Disney. La empresa opera multiples parques tematicos Legoland y Lego Discovery Centers en todo el mundo. Los productos Lego Education se utilizan en aulas globalmente para la ensenanza de materias STEM. Lego es constantemente clasificada entre las marcas mas respetadas del mundo. Mas alla de ser un juguete, Lego se ha convertido en un medio de expresion creativa. La empresa esta comprometida con la sostenibilidad, buscando utilizar materiales sostenibles en todos sus productos para 2030. Lego sigue siendo una empresa familiar dedicada a la calidad, la creatividad y el aprendizaje a traves del juego.",
    "de": "Die Lego Gruppe ist ein danischer Spielzeughersteller mit Hauptsitz in Billund, Danemark. Gegrundet 1932 von Ole Kirk Christiansen als kleine Tischlerwerkstatt, die Holzspielzeug produzierte. Der Name Lego wurde 1934 angenommen und leitet sich vom danischen leg godt (spiel gut) ab. 1949 begann Lego mit der Produktion der beruhmten Kunststoffsteine, die die Spielzeugindustrie revolutionierten. Die Produktlinien umfassen Lego City, Creator, Technic, Classic, Duplo und lizenzierte Themen wie Star Wars, Harry Potter, Marvel, DC und Disney. Das Unternehmen betreibt mehrere Legoland-Freizeitparks und Lego Discovery Centers weltweit. Lego Education Produkte werden in Schulen fur den MINT-Unterricht eingesetzt. Lego gehort durchgangig zu den angesehensten und vertrauenswurdigsten Unternehmen der Welt. Uber das Spielzeug hinaus ist Lego zu einem Medium fur kreativen Ausdruck geworden. Das Unternehmen setzt sich fur Nachhaltigkeit ein und strebt an, bis 2030 nachhaltige Materialien in allen Kernprodukten zu verwenden. Lego bleibt ein Familienunternehmen, das sich Qualitat, Kreativitat und Lernen durch Spielen verschrieben hat.",
    "pt": "O Grupo Lego e uma empresa dinamarquesa de brinquedos sediada em Billund, Dinamarca. Fundado por Ole Kirk Christiansen em 1932 como uma pequena oficina de carpintaria que produzia brinquedos de madeira. O nome Lego foi adotado em 1934, derivado do dinamarques leg godt (brincar bem). Em 1949, a Lego comecou a produzir seus iconicos blocos de plastico interligaveis, revolucionando a industria de brinquedos. As linhas de produtos incluem Lego City, Creator, Technic, Classic, Duplo e temas licenciados de Star Wars, Harry Potter, Marvel, DC e Disney. A empresa opera varios parques tematicos Legoland e Lego Discovery Centers globalmente. Os produtos Lego Education sao usados em salas de aula para ensino de STEM. A Lego e consistentemente classificada entre as marcas mais respeitadas do mundo. Alem de brinquedo, a Lego tornou-se um meio de expressao criativa. A empresa esta comprometida com a sustentabilidade, visando usar materiais sustentaveis em todos os produtos ate 2030. A Lego permanece uma empresa familiar dedicada a qualidade, criatividade e aprendizado atraves da brincadeira.",
    "ru": "Группа Lego датская компания по производству игрушек со штаб-квартирой в Биллунде, Дания. Основана Оле Кирком Кристиансеном в 1932 году как небольшая столярная мастерская по производству деревянных игрушек. Название Lego было принято в 1934 году и происходит от датского leg godt (играй хорошо). В 1949 году Lego начала производство знаменитых пластиковых соединяющихся кубиков, произведя революцию в индустрии игрушек. Линейки продукции включают Lego City, Creator, Technic, Classic, Duplo и лицензионные серии: Star Wars, Harry Potter, Marvel, DC и Disney. Компания управляет несколькими парками Legoland и Lego Discovery Centers по всему миру. Продукты Lego Education используются в школах для преподавания STEM. Lego постоянно входит в число самых уважаемых и надежных компаний мира. Помимо игрушек, Lego стала средством творческого самовыражения. Компания стремится к устойчивому развитию, планируя к 2030 году использовать экологичные материалы во всех основных продуктах. Lego остается семейной компанией, приверженной качеству, креативности и обучению через игру.",
    "ar": "مجموعة ليغو هي شركة دنماركية لتصنيع الألعاب يقع مقرها الرئيسي في بلوند، الدنمارك. أسسها أولي كيرك كريستيانسن في عام 1932 كورقة نجارة صغيرة تنتج الألعاب الخشبية. تم اعتماد اسم ليغو في عام 1934، وهو مشتق من العبارة الدنماركية leg godt (العب جيدا). في عام 1949، بدأت ليغو إنتاج مكعباتها البلاستيكية المتشابكة الشهيرة التي أحدثت ثورة في صناعة الألعاب. تشمل خطوط الإنتاج ليغو سيتي وكرييتور وتكنيك وكلاسيك ودوبلو وسلسلة مرخصة من ستار وورز وهاري بوتر ومارفل ودي سي وديزني. تدير الشركة العديد من منتزهات ليغولاند الترفيهية ومراكز ليغو ديسكفري حول العالم. تُستخدم منتجات ليغو إديوكيشن في الفصول الدراسية لتدريس مواد STEM. تُصنف ليغو باستمرار من بين أكثر العلامات التجارية احتراما وثقة في العالم. إلى جانب كونها لعبة، أصبحت ليغو وسيلة للتعبير الإبداعي. تلتزم الشركة بالاستدامة، بهدف استخدام مواد مستدامة في جميع المنتجات الأساسية بحلول عام 2030. تظل ليغو شركة عائلية مكرسة للجودة والإبداع والتعلم من خلال اللعب."
})
