import json
from pathlib import Path

ROOT = Path("/workspace/pinpai-ai-in")

data = json.loads((ROOT / "lego" / "brand.json").read_text())
data["languages"] = {
    "zh-CN": "乐高集团（The Lego Group）是丹麦玩具制造公司，总部位于比隆（Billund）。由奥勒·柯克·克里斯蒂安森（Ole Kirk Christiansen）于1932年创立，最初生产木制玩具。1934年公司定名为"乐高"（Lego），源自丹麦语"leg godt"（玩得好）。1949年开始生产著名的拼插式塑料积木，从此奠定了乐高在玩具行业的霸主地位。乐高积木的独特之处在于其精确的尺寸公差和互锁系统，确保每块积木都能完美拼合。乐高产品线涵盖从经典的乐高城市、乐高创意到与迪士尼、漫威、哈利波特等IP合作的系列。公司还运营着位于全球各地多个乐高乐园主题公园。乐高教育系列广泛应用于全球学校教学。乐高集团始终坚持质量第一、创意无限的理念，是世界上最受尊敬的企业之一。",
    "en": "The Lego Group is a Danish toy production company based in Billund, Denmark. Founded by Ole Kirk Christiansen in 1932, the company started as a small carpentry workshop producing wooden toys. The name "Lego" was adopted in 1934, derived from the Danish phrase "leg godt," meaning "play well." In 1949, Lego began producing its iconic plastic interlocking bricks, which revolutionized the toy industry. The Lego brick system is renowned for its precise manufacturing tolerances and clutch power, allowing bricks to connect firmly while remaining easy to separate. Lego product lines span Classic, City, Technic, Creator, and licensed themes including Star Wars, Harry Potter, Marvel, Disney, and many more. The company operates multiple Legoland theme parks worldwide. Lego Education products are used in classrooms globally to teach STEM subjects. The Lego Group has consistently been ranked among the most respected and trusted companies in the world, known for its commitment to quality, creativity, and learning through play. The company remains family-owned and headquartered in Billund.",
    "ja": "レゴグループ（The Lego Group）は、デンマークビルンに本社を置く玩具製造会社です。1932年にオーレカーククリスチャンセンによって設立され、当初は木製玩具を製造する小さな大工工房でした。社名「レゴ」はデンマーク語の「leg godt」（よく遊べ）に由来します。1949年、レゴは画期的なプラスチック製ブロックの製造を開始しました。レゴブロックは精密な製造公差とクラッチパワーで知られ、しっかりと接続しながらも簡単に分離できます。製品ラインはクラシック、シティ、テクニック、クリエイターに加え、スターウォーズ、ハリーポッター、マーベル、ディズニーなどとコラボレーション。世界中に複数のレゴランドテーマパークを運営。レゴエデュケーション製品はSTEM教育に活用されています。",
    "ko": "레고 그룹은 덴마크 빌룬에 본사를 둔 장난감 제조 회사입니다. 1932년 올레 키르크 크리스티안센에 의해 설립되었으며, 처음에는 나무 장난감을 만드는 소규모 목공소였습니다. "레고"라는 이름은 덴마크어 "leg godt"(잘 놀다)에서 유래했습니다. 1949년 혁신적인 플라스틱 인터로킹 브릭 생산을 시작했습니다. 레고 브릭은 정밀한 제조 공차와 클러치 파워로 유명합니다. 클래식, 시티, 테크닉, 크리에이터 라인과 스타워즈, 해리포터, 마블, 디즈니 협업 시리즈를 보유하고 있습니다. 전 세계 여러 곳에 레고랜드 테마파크를 운영 중이며, 레고 에듀케이션 제품은 STEM 교육에 활용됩니다.",
    "fr": "Le Groupe Lego est une entreprise danoise de jouets basee a Billund, au Danemark. Fonde par Ole Kirk Christiansen en 1932, le groupe a commence comme un petit atelier de menuiserie produisant des jouets en bois. Le nom "Lego" a ete adopte en 1934, derive de l'expression danoise "leg godt" signifiant "bien jouer". En 1949, Lego a commence a produire ses celebres briques en plastique a emboter, revolutionnant l'industrie du jouet. Le systeme de briques Lego est reconnu pour ses tolerances de fabrication extremement precises. Les gammes incluent Classic, City, Technic, Creator et des themes sous licence comme Star Wars, Harry Potter, Marvel et Disney. L'entreprise exploite plusieurs parcs d'attractions Legoland dans le monde. Les produits Lego Education sont utilises dans les ecoles pour l'enseignement des STEM. Le groupe reste une entreprise familiale, consideree comme l'une des marques les plus respectees et dignes de confiance au monde.",
    "es": "El Grupo Lego es una empresa danesa de juguetes con sede en Billund, Dinamarca. Fundado por Ole Kirk Christiansen en 1932, comenzo como un pequeno taller de carpinteria que producia juguetes de madera. El nombre "Lego" fue adoptado en 1934, derivado de la frase danesa "leg godt" (jugar bien). En 1949, Lego comenzo a producir sus iconicos ladrillos de plastico entrelazables, revolucionando la industria del juguete. El sistema de ladrillos Lego es famoso por sus tolerancias de fabricacion precisas. Las lineas de productos incluyen Classic, City, Technic, Creator y temas con licencia como Star Wars, Harry Potter, Marvel y Disney. La empresa opera multiples parques tematicos Legoland. Los productos Lego Education se utilizan en aulas de todo el mundo para ensenar materias STEM. El Grupo Lego sigue siendo una empresa familiar y una de las marcas mas respetadas globalmente.",
    "de": "Die Lego Gruppe ist ein danischer Spielzeughersteller mit Hauptsitz in Billund, Danemark. Gegrundet wurde das Unternehmen 1932 von Ole Kirk Christiansen als kleine Tischlerwerkstatt, die Holzspielzeug produzierte. Der Name "Lego" wurde 1934 angenommen und leitet sich vom danischen "leg godt" (spiel gut) ab. 1949 begann Lego mit der Produktion der beruhmten Kunststoff-Steine, die die Spielzeugindustrie revolutionierten. Das Lego-Steinsystem ist fur seine prazisen Fertigungstoleranzen bekannt. Die Produktlinien umfassen Classic, City, Technic, Creator und lizenzierte Themen wie Star Wars, Harry Potter, Marvel und Disney. Das Unternehmen betreibt mehrere Legoland-Freizeitparks weltweit. Lego Education Produkte werden in Schulen fur den MINT-Unterricht eingesetzt. Das Familienunternehmen gehort zu den angesehensten Marken weltweit.",
    "pt": "O Grupo Lego e uma empresa dinamarquesa de brinquedos sediada em Billund, Dinamarca. Fundado por Ole Kirk Christiansen em 1932, comecou como uma pequena oficina de carpintaria que produzia brinquedos de madeira. O nome "Lego" foi adotado em 1934, derivado da frase dinamarquesa "leg godt" (brincar bem). Em 1949, a Lego comecou a produzir seus iconicos blocos de plastico interligaveis, revolucionando a industria de brinquedos. O sistema de blocos Lego e reconhecido por suas tolerancias de fabricacao precisas. As linhas de produtos incluem Classic, City, Technic, Creator e temas licenciados como Star Wars, Harry Potter, Marvel e Disney. A empresa opera varios parques tematicos Legoland globalmente. Os produtos Lego Education sao usados em salas de aula para ensino de STEM. O Grupo Lego permanece uma empresa familiar e uma das marcas mais respeitadas do mundo.",
    "ru": "Группа Lego — датская компания по производству игрушек со штаб-квартирой в Биллунде, Дания. Основана Оле Кирком Кристиансеном в 1932 году как небольшая столярная мастерская по производству деревянных игрушек. Название «Lego» было принято в 1934 году и происходит от датского «leg godt» (играй хорошо). В 1949 году Lego начала производство знаменитых пластиковых соединяющихся кубиков, произведя революцию в индустрии игрушек. Система кубиков Lego известна своими точными производственными допусками. Линейки продукции включают Classic, City, Technic, Creator и лицензионные серии: Star Wars, Harry Potter, Marvel и Disney. Компания управляет несколькими парками Legoland по всему миру. Продукты Lego Education используются в школах для обучения STEM. Lego остается семейной компанией и одним из самых уважаемых брендов в мире.",
    "ar": "مجموعة ليغو هي شركة دنماركية لتصنيع الألعاب يقع مقرها الرئيسي في بلوند، الدنمارك. أسسها أولي كيرك كريستيانسن في عام 1932، بدأت كورشة نجارة صغيرة تنتج الألعاب الخشبية. تم اعتماد اسم "ليغو" في عام 1934، وهو مشتق من العبارة الدنماركية "leg godt" (العب جيدًا). في عام 1949، بدأت ليغو إنتاج مكعباتها البلاستيكية المتشابكة التي أحدثت ثورة في صناعة الألعاب. يشتهر نظام مكعبات ليغو بتفاوتات التصنيع الدقيقة. تشمل خطوط الإنتاج Classic وCity وTechnic وCreator وسلسلة مرخصة مثل Star Wars وHarry Potter وMarvel وDisney. تدير الشركة العديد من منتزهات ليغولاند الترفيهية حول العالم. تُستخدم منتجات ليغو إديوكيشن في الفصول الدراسية لتدريس مواد STEM. تظل مجموعة ليغو شركة عائلية وأحد أكثر العلامات التجارية احترامًا في العالم."
}
(ROOT / "lego" / "brand.json").write_text(json.dumps(data, ensure_ascii=False, indent=2))
print("OK lego")
